server {
    listen 80;
    server_name aaa.sy99.cloud;

    # 1. 정적 파일 (Nginx 주황색 페이지) 설정
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}